/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import br.unesp.igce.gerenciador_mangas_HQs.Manga;
import br.unesp.igce.gerenciador_mangas_HQs.SavePoint;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Sanchez
 */
public class Tela_Mostrar_Todos_Mangas extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Mostrar_Todos_Mangas
     */
    public Tela_Mostrar_Todos_Mangas() {
        super("Mostrar todos Mangas");
        initComponents();
        List<Manga> Manga_Lista;
        SavePoint save = new SavePoint();
        
        if(save.ExistManga()){
            Manga_Lista = save.ReadManga();
        }else{
            Manga_Lista = new ArrayList<Manga>();
        }
        
        DefaultListModel lista = new DefaultListModel(); 
        for(int i=0;i<Manga_Lista.size();i++){
            String nome = Manga_Lista.get(i).getNome();
            for(int i2 =0;i2<Manga_Lista.get(i).getFasciculos().size();i2++){
               int Idioma = Manga_Lista.get(i).getFasciculos().get(i2).getIdioma();
               int tipo = Manga_Lista.get(i).getFasciculos().get(i2).getTipo();
               String nome_tipo = "";
               String nome_Idioma = "";
               
               if(tipo == 0){
                   nome_tipo = "Tankobon";
               }else{
                   nome_tipo = "Meio-Tankobon";
               }
               switch(Idioma){
                   case 0:
                       nome_Idioma = "Portugês";
                       break;
                   case 1:
                       nome_Idioma = "Japonês";
                       break;
                   case 2:
                       nome_Idioma = "Inglês";
                       break;
                   case 3:
                       nome_Idioma = "Italiano";
                       break;
                   case 4:
                       nome_Idioma = "Espanhol";
                       break;
                   case 5:
                       nome_Idioma = "Holandes";
                       break;
                   case 6:
                       nome_Idioma = "Francês";
                       break;
               }
            
               if(Manga_Lista.get(i).getFasciculos().get(i2).getVolume() != -1){
                lista.addElement("Nome: "+nome+"     Volume: "+Integer.toString(Manga_Lista.get(i).getFasciculos().get(i2).getVolume())+"         Idioma: "+nome_Idioma + "          Tipo: "+nome_tipo);
               }else{
                   lista.addElement("Nome: "+nome+"     Volume: Especial"+"         Idioma: "+nome_Idioma + "          Tipo: "+nome_tipo);
               }
            }
        lista.addElement("");
        lista.addElement("");
        }
        jList1.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Mostrar_Todos_Mangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Mostrar_Todos_Mangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Mostrar_Todos_Mangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Mostrar_Todos_Mangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Mostrar_Todos_Mangas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
